# Generated by Django 4.1.7 on 2023-04-01 19:29

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, upload_to=myapp.models.UniqueFilename('videos/')),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
