# Generated by Django 4.1.7 on 2023-04-03 15:09

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_video_video_file_alter_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=myapp.models.UniqueFilename('video_thumbnails/')),
        ),
    ]
